[[languages.cpp.environments]]
CXX = "g++"
CXXFLAGS = ["-std=c++20", "-Ofast", "-Wall", "-Wextra", "-Wshadow", "-Wconversion", "-Werror", "-fsanitize=address,undefined", "-fno-sanitize-recover=address,undefined", "-DDEBUG"]
