name: gch test

permissions:
  contents: read
  pull-requests: read

on:
  push:
  pull_request:

jobs:
  gch_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: gch File Generate Test
      run: |
        chmod u+x ./gch_test.sh
        ./gch_test.sh
